//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ID { get; set; }
        public string C__doc { get; set; }
        public System.DateTime Date_registrate { get; set; }
        public string FIO { get; set; }
        public string Correspondent { get; set; }
        public Nullable<System.DateTime> Date_doc { get; set; }
        public Nullable<int> Index_doc { get; set; }
        public string Adress { get; set; }
        public string Resolution { get; set; }
        public string Executor { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<System.DateTime> Executed { get; set; }
        public string Result { get; set; }
        public string C__dela { get; set; }
        public string C__toma { get; set; }
        public string C__ctr { get; set; }
        public string FIle { get; set; }
    }
}
